import './global.css';

console.log('layout.tsx loaded 2');

export const metadata = {
  title: 'Welcome to my-new-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
