name: 'Extract Issue Number from Branch'
description: 'Extracts the branch name and the issue number (if any) from the Git ref.'
inputs:
  branch:
    description: 'The name of the branch to check'
    required: true
outputs:
  issue_number:
    description: 'The extracted issue number from the branch name'
    value: ${{ steps.extract.outputs.issue_number }}
runs:
  using: 'composite'
  steps:
    - id: extract
      run: |
        ISSUE_NUMBER=$(echo "${{ inputs.branch }}" | grep -oE '^[0-9]+')
        echo "issue_number=$(echo $ISSUE_NUMBER)" >> $GITHUB_OUTPUT
      shell: bash
