# Create a pull request when a new branch is created
name: Create PR on Branch Created
on:
  create:
    branches:
      - '*'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'New branch created: ${{ github.ref }}'
          body: 'A new branch has been created: ${{ github.ref }}'
          base: main
          head: ${{ github.ref }}
          draft: true
          commit-message: 'Create pull request for new branch'
