# This workflow is triggered when a pull request is opened and not in draft mode
# It adds a label "to review" to the issue associated with the pull request
name: Add Label when PR is Approved
on:
  pull_request_review:
    types: [submitted]

permissions:
  issues: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-labels:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v4
      - name: Find linked issue
        id: extract
        run: |
          # Recherche une référence de type #123 dans le body de la PR
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "❌ No issue number found in PR body"
            exit 1
          else
            echo "Found issue: $ISSUE_NUMBER"
            echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi
      - name: Add label to linked issue
        run: gh issue edit ${{ steps.extract.outputs.issue_number }} --add-label "qa" --remove-label "ready-for-review"
      - run: gh issue comment ${{ steps.extract.outputs.issue_number }} --body "This issue is ready for QA review. The environment is deployed."
  deploy:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
