# This workflow is triggered when a pull request is opened and not in draft mode
# It adds a label "to review" to the issue associated with the pull request
name: Add Label to Issue on PR Ready for review
on:
  pull_request:
    types: [ready_for_review]

permissions:
  issues: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find linked issue
        id: extract
        run: |
          # Recherche une référence de type #123 dans le body de la PR
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "❌ No issue number found in PR body"
            exit 1
          else
            echo "Found issue: $ISSUE_NUMBER"
            echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi
      - name: Add label to linked issue
        run: gh issue edit ${{ steps.extract.outputs.issue_number }} --add-label "ready-for-review"
