# This workflow is triggered when a pull request is opened and not in draft mode
# It adds a label "to review" to the issue associated with the pull request
name: Add Label when PR is Approved

on:
  pull_request_review:
    types: [submitted]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-labels:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract issue number from PR title
        id: extract
        uses: ./.github/actions/extract-issue-from-pr-title
        with:
          pr_title: ${{ github.event.pull_request.title }}
      - run: |
          gh issue edit ${{ steps.extract.outputs.issue_number }} --remove-label "ready for review"
          gh issue edit ${{ steps.extract.outputs.issue_number }} --add-label "ready for qa"

  deploy:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    environment: staging
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract issue from branch name
        id: extract
        uses: ./.github/actions/extract-issue-from-branch
        with:
          branch: ${{ github.ref_name }}
      - run: echo "Deploying to staging environment..."
      - run: gh issue comment ${{ steps.extract.outputs.issue_number }} --body "This issue is ready for QA review. The environment is deployed."
