# This workflow is triggered when a pull request is opened and not in draft mode
# It adds a label "to review" to the issue associated with the pull request
name: Add Label to Issue on PR Opened
on:
  pull_request:
    types: [ready_for_review]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Find linked issue
        id: find-issue
        run: |
          # Recherche une référence de type #123 dans le body de la PR
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No linked issue found."
            echo "issue_number=" >> $GITHUB_OUTPUT
          else
            echo "Found issue: $ISSUE_NUMBER"
            echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi
      - name: Add label to linked issue
        if: steps.find-issue.outputs.issue_number != ''
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.find-issue.outputs.issue_number }}/labels \
            -d '{"labels": ["ready-for-review"]}'
